---
namespace: 'r_pufky'
name: 'game'
version: '13.0.3'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: |
  Host game servers.
license_file: 'LICENSE'
tags:
  - 'steam'
  - 'steamcmd'
  - 'wine'
  - 'winetricks'
  - 'linux'
  - 'windows'
  - 'server'
dependencies:
  'r_pufky.lib': '>=13.0.4,<14.0.0'
  'r_pufky.deb': '>=13.0.5,<14.0.0'
  'community.general': '=10.6.0'

repository: 'https://github.com/r-pufky/ansible_collection_game'
documentation: 'https://github.com/r-pufky/ansible_colection_srv/docs/README.md'
homepage: 'https://github.com/r-pufky/ansible_collection_game'
issues: 'https://github.com/r-pufky/ansible_collection_game/issues'

build_ignore:
  - '*molecule/*'  # Do not include molecule testing in release.
  - 'ansible.env'  # Development ansible environment.
  - '.ansible'  # Ansible collection cache for role testing.
  - '.vscode'  # VSCodium settings.
  - 'TODO.md'  # Development staging todo messages.
  - 'COMMIT.md'  # Development staging commit messages.
  - 'docs/*'  # Development docs are a separate repo and not end user.
