---
namespace: 'r_pufky'
name: 'game'
version: '1.1.2'
readme: 'README.md'
authors:
  - 'Robert Pufky <rpufky@gmail.com> (https://github.com/r-pufky)'
description: 'Host game servers.'
license_file: 'LICENSE'
tags:
  - 'steam'
  - 'steamcmd'
  - 'wine'
  - 'winetricks'
  - 'linux'
  - 'windows'
  - 'server'
dependencies:
  'r_pufky.data': '>=3.2.2,<4.0.0'
  'r_pufky.deb': '>=4.1.1,<5.0.0'
  'community.general': '>=12.5.0,<13.0.0'

repository: 'https://github.com/r-pufky/ansible_collection_game'
documentation: 'https://r-pufky.github.io/ansible_docs'
homepage: 'https://github.com/r-pufky/ansible_collection_game'
issues: 'https://github.com/r-pufky/ansible_collection_game/issues'

# Do not include: testing, environments, caches, IDE settings, or staging
# messages in release tarball.
build_ignore:
  - '*.ansible'
  - '*.gitignore'
  - '*.gitattributes'
  - '*.gitmodules'
  - '*.git'
  - '*.venv'
  - '*.envrc'
  - '*.vscode'
  - '*molecule'
  - 'ansible.env'
  - 'pyproject.toml'
  - 'uv.lock'
  - 'TODO.md'
  - 'COMMIT.md'
